from pessoa import Pessoa

joao = Pessoa('João', 20, False, False)
print(joao.nome, joao.idade, joao.comendo, joao.falando)
print("----------------------------------------------------")
maria = Pessoa('Maria', 25)
maria.imprime_dados()
print("----------------------------------------------------")
joao.comer("Pizza")
joao.comer("Picanha")
joao.parar_comer()
print("----------------------------------------------------")
maria.comer("Lasanha")
maria.parar_comer()
print("----------------------------------------------------")
joao.falar("Olá, meu nome é João")
joao.falar("Tudo bem?")
joao.parar_falar()
print("----------------------------------------------------")
maria.falar("Tudo ótimo João! E você?")
maria.parar_falar()
